
#ifndef HAL_CONSTANTS_DMA_H
#define HAL_CONSTANTS_DMA_H

#define DMA_PRIORITY_BACKGROUND     0
#define DMA_PRIORITY_LOW            1
#define DMA_PRIORITY_HIGH           2
#define DMA_PRIORITY_IMMEDIATE      3

typedef enum {
    _DMA_PRIORITY_BACKGROUND = DMA_PRIORITY_BACKGROUND,
    _DMA_PRIORITY_LOW = DMA_PRIORITY_LOW,
    _DMA_PRIORITY_HIGH = DMA_PRIORITY_HIGH,
    _DMA_PRIORITY_IMMEDIATE = DMA_PRIORITY_IMMEDIATE
} DMA_PRIORITY_t;

#define DMA_XFER_MEMORY_MEMORY      0
#define DMA_XFER_MEMORY_PERIPH      1
#define DMA_XFER_PERIPH_MEMORY      2
#define DMA_XFER_PERIPH_PERIPH      3

typedef enum {
    _DMA_XFER_MEMORY_MEMORY = DMA_XFER_MEMORY_MEMORY,
    _DMA_XFER_MEMORY_PERIPH = DMA_XFER_MEMORY_PERIPH,
    _DMA_XFER_PERIPH_MEMORY = DMA_XFER_PERIPH_MEMORY,
    _DMA_XFER_PERIPH_PERIPH = DMA_XFER_PERIPH_PERIPH
} DMA_TRANSFER_TYPE_t;

#define DMA_REQ_NONE                0
#define DMA_REQ_SOFTWARE            1
#define DMA_REQ_DST                 2
#define DMA_REQ_SRC                 3

typedef enum {
    _DMA_REQ_NONE = DMA_REQ_NONE,
    _DMA_REQ_SOFTWARE = DMA_REQ_SOFTWARE,
    _DMA_REQ_DST = DMA_REQ_DST,
    _DMA_REQ_SRC = DMA_REQ_SRC,
} DMA_REQUEST_TYPE_t;

#endif      