
#ifndef HAL_CONSTANTS_QDELAY_H
#define HAL_CONSTANTS_QDELAY_H

#define QDELAY_PROVIDER_CPU     0
#define QDELAY_PROVIDER_SYSTICK 1
#define QDELAY_PROVIDER_TIMER   2
#define QDELAY_PROVIDER_DWT     3

typedef enum {
    _QDELAY_PROVIDER_CPU        = QDELAY_PROVIDER_CPU,
    _QDELAY_PROVIDER_SYSTICK    = QDELAY_PROVIDER_SYSTICK,
    _QDELAY_PROVIDER_TIMER      = QDELAY_PROVIDER_TIMER,
    _QDELAY_PROVIDER_DWT        = QDELAY_PROVIDER_DWT
} QDELAY_PROVIDER_t;

#endif
