#ifndef HAL_CONSTANTS_TIMER_H
#define HAL_CONSTANTS_TIMER_H

#define TIMER_MODE_STOPPED  0
#define TIMER_MODE_ONESHOT  1
#define TIMER_MODE_PERIODIC 2
#define TIMER_MODE_COUNTING 3
#define TIMER_MODE_UPDOWN   4

typedef enum {
    _TIMER_MODE_STOPPED  = TIMER_MODE_STOPPED, 
    _TIMER_MODE_ONESHOT  = TIMER_MODE_ONESHOT,
    _TIMER_MODE_PERIODIC = TIMER_MODE_PERIODIC, 
    _TIMER_MODE_COUNTING = TIMER_MODE_COUNTING, 
    _TIMER_MODE_UPDOWN   = TIMER_MODE_UPDOWN,
} TIMER_MODE_t;

#define TIMER_OUTMODE_NONE      0  // No Output
#define TIMER_OUTMODE_PWM       1  // Reset/Set
#define TIMER_OUTMODE_NPWM      2  // Set/Reset
#define TIMER_OUTMODE_TOGGLE    3  // Toggle, NotImplemented

typedef enum {
    _TIMER_OUTMODE_NONE    = TIMER_OUTMODE_NONE,
    _TIMER_OUTMODE_PWM     = TIMER_OUTMODE_PWM,   
    _TIMER_OUTMODE_NPWM    = TIMER_OUTMODE_NPWM,
    _TIMER_OUTMODE_TOGGLE  = TIMER_OUTMODE_TOGGLE,
} TIMER_OUTMODE_t;


#define TIMER_WIDTH_8B          1
#define TIMER_WIDTH_16B         2
#define TIMER_WIDTH_32B         4

typedef enum {
    _TIMER_WIDTH_8B  = TIMER_WIDTH_8B,
    _TIMER_WIDTH_16B = TIMER_WIDTH_16B,
    _TIMER_WIDTH_32B = TIMER_WIDTH_32B,
} TIMER_WIDTH_t;

#define TIMER_COUNTER_TYPE_UP       0
#define TIMER_COUNTER_TYPE_UPDOWN   1

typedef enum {
    _TIMER_COUNTER_TYPE_UP = TIMER_COUNTER_TYPE_UP,
    _TIMER_COUNTER_TYPE_UPDOWN = TIMER_COUNTER_TYPE_UPDOWN,
} TIMER_COUNTER_TYPE_t;

#define TIMER_TRIGGEN_NONE          0
#define TIMER_TRIGGEN_START         1
#define TIMER_TRIGGEN_TOP           2
#define TIMER_TRIGGEN_CM1           3
#define TIMER_TRIGGEN_CM2           4
#define TIMER_TRIGGEN_CM3           5
#define TIMER_TRIGGEN_CM4           6
#define TIMER_TRIGGEN_CM5           7
#define TIMER_TRIGGEN_CM6           8

typedef enum {
    _TIMER_TRIGGEN_NONE  = TIMER_TRIGGEN_NONE,
    _TIMER_TRIGGEN_START = TIMER_TRIGGEN_START,
    _TIMER_TRIGGEN_TOP   = TIMER_TRIGGEN_TOP,
    _TIMER_TRIGGEN_CM1   = TIMER_TRIGGEN_CM1,
    _TIMER_TRIGGEN_CM2   = TIMER_TRIGGEN_CM2,
    _TIMER_TRIGGEN_CM3   = TIMER_TRIGGEN_CM3,
    _TIMER_TRIGGEN_CM4   = TIMER_TRIGGEN_CM4,
    _TIMER_TRIGGEN_CM5   = TIMER_TRIGGEN_CM5,
    _TIMER_TRIGGEN_CM6   = TIMER_TRIGGEN_CM6,
} TIMER_TRIGGEN_t;

#endif
